tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "laurent22/massren"
tap "parera10/csshx"
brew "gdbm"
brew "libyaml"
brew "readline"
brew "sqlite"
brew "python"
brew "ansible"
brew "autoconf"
brew "awscli"
brew "bash-completion"
brew "cmake"
brew "coreutils"
brew "curl"
brew "direnv"
brew "faac"
brew "gmp"
brew "nettle"
brew "lame"
brew "tesseract"
brew "x264"
brew "xvid"
brew "fping"
brew "git"
brew "git-flow"
brew "go"
brew "oniguruma"
brew "jq"
brew "libav"
brew "mas"
brew "python@2"
brew "mongodb"
brew "ngrep"
brew "nmap"
brew "opencv"
brew "openssl@1.1"
brew "packer"
brew "pkg-config"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-gemset"
brew "rsync"
brew "ssh-copy-id"
brew "stoken"
brew "tfenv"
brew "tree"
brew "unrar"
brew "vault"
brew "watch"
brew "wget"
brew "laurent22/massren/massren"
brew "parera10/csshx/csshx"
cask "adobe-acrobat-reader"
cask "appcleaner"
cask "avidemux"
cask "awa"
cask "burn"
cask "caffeine"
cask "chrome-remote-desktop-host"
cask "clipy"
cask "cyberduck"
cask "firefox"
cask "gas-mask"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "handbrake"
cask "iterm2"
cask "java"
cask "macdown"
cask "marp"
cask "openemu"
cask "opera"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "simple-comic"
cask "skype"
cask "sublime-text"
cask "the-unarchiver"
cask "tunnelblick"
cask "vlc"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "Alfred", id: 405843582
mas "Blackmagic Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "TUT Touch Typing", id: 962713362
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
