tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'kosaka-kazuhiro/mitaka', 'https://ghe.ca-tools.org/kosaka-kazuhiro/homebrew-mitaka'
tap 'laurent22/massren'
brew 'libyaml'
brew 'gdbm'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'ansible'
brew 'autoconf'
brew 'bash-completion'
brew 'gmp'
brew 'coreutils'
brew 'csshx'
brew 'curl'
brew 'git'
brew 'go'
brew 'direnv'
brew 'faac'
brew 'fping'
brew 'oniguruma'
brew 'jq'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'libav'
brew 'mas'
brew 'nettle'
brew 'packer'
brew 'ssh-copy-id'
brew 'stoken'
brew 'tree'
brew 'wget'
brew 'homebrew/dupes/rsync'
brew 'laurent22/massren/massren'
cask 'adobe-reader'
cask 'alfred'
cask 'android-file-transfer'
cask 'appcleaner'
cask 'burn'
cask 'caffeine'
cask 'cheatsheet'
cask 'chrome-remote-desktop-host'
cask 'clipmenu'
cask 'cyberduck'
cask 'dropbox'
cask 'duet'
cask 'evernote'
cask 'flux'
cask 'gas-mask'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'java'
cask 'karabiner'
cask 'macdown'
cask 'mitaka'
cask 'nosleep'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'securid'
cask 'skype'
cask 'slack'
cask 'textwrangler'
cask 'the-unarchiver'
cask 'vlc'
mas 'Alfred', id: 405843582
mas 'Xcode', id: 497799835
mas 'EchofonLite', id: 403858460
mas 'Keynote', id: 409183694
mas 'Microsoft OneNote', id: 784801555
mas '1Password', id: 443987910
mas 'Pocket', id: 568494494
mas 'Slack', id: 803453959
mas 'Wunderlist', id: 410628904
mas 'Blackmagic Disk Speed Test', id: 425264550
mas 'LINE', id: 539883307
